language: node_js
node_js: stable
branches:
  only: hexo-project
cache: 
  directories:
    - node_modules
before_install:
  - npm install -g hexo-cli
install: 
  - npm install
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo g
after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Build"
  - git config user.name "zsStrike"
  - git config user.email "2439758713@qq.com"
  - git push --quiet --force https://5faa7930eb33511fdb9d446c596fb45760bbb1de@github.com/zsstrike.github.io.git master
